class: net.gtaun.shoebill.fcnpc.Wrapper
name: FCNPC-Wrapper Plugin
version: 1.0-SNAPSHOT
buildNumber: 0
buildDate: Unknown
authors: 123marvin123
description: This plugin is a wrapper for the FCNPC plugin.